version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_dlouky
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=dlouky
      - POSTGRES_PASSWORD=dlouky
      - POSTGRES_DB=dlouky
    ports:
      - 5432:5432
  # web:
  #   build: .
  #   command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --username dlouky --password dlouky && python manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - .:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db
volumes:
  postgres_data: